// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPvUVX9fo72nr5Jx7kGR6mPLUHB6X3FTU',
    appId: '1:448930784590:web:6b3ce8d3f30e27b5b92a1f',
    messagingSenderId: '448930784590',
    projectId: 'kibabii-nest',
    authDomain: 'kibabii-nest.firebaseapp.com',
    storageBucket: 'kibabii-nest.firebasestorage.app',
    measurementId: 'G-NKB9CLE2VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CfGrR6m7n8GoDFhXfm939V9Vee_dDPQ',
    appId: '1:448930784590:android:0d965209231a095db92a1f',
    messagingSenderId: '448930784590',
    projectId: 'kibabii-nest',
    storageBucket: 'kibabii-nest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxhdIkAXQOeQEo3P4E9uUjrsSt5QpQYL8',
    appId: '1:448930784590:ios:c5bb2f08e64ac3eeb92a1f',
    messagingSenderId: '448930784590',
    projectId: 'kibabii-nest',
    storageBucket: 'kibabii-nest.firebasestorage.app',
    androidClientId: '448930784590-5bmegbirhtopig0r2hql06a62j9lnoo8.apps.googleusercontent.com',
    iosClientId: '448930784590-7msl987g8fn5iq6vchf7vsqcao997k58.apps.googleusercontent.com',
    iosBundleId: 'com.kibabiinest.nest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxhdIkAXQOeQEo3P4E9uUjrsSt5QpQYL8',
    appId: '1:448930784590:ios:76a88a8d46a2faebb92a1f',
    messagingSenderId: '448930784590',
    projectId: 'kibabii-nest',
    storageBucket: 'kibabii-nest.firebasestorage.app',
    androidClientId: '448930784590-5bmegbirhtopig0r2hql06a62j9lnoo8.apps.googleusercontent.com',
    iosClientId: '448930784590-h47kti535sq61rhigaibpf9af1sc99sq.apps.googleusercontent.com',
    iosBundleId: 'com.kibabiinest.kibabiiNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPvUVX9fo72nr5Jx7kGR6mPLUHB6X3FTU',
    appId: '1:448930784590:web:21044943834fc736b92a1f',
    messagingSenderId: '448930784590',
    projectId: 'kibabii-nest',
    authDomain: 'kibabii-nest.firebaseapp.com',
    storageBucket: 'kibabii-nest.firebasestorage.app',
    measurementId: 'G-Y39DPC560L',
  );
}
